"""sessions table

Revision ID: 87ab4a45625f
Revises: 75c6b301b14b
Create Date: 2025-01-04 08:02:17.542764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87ab4a45625f'
down_revision = '75c6b301b14b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('session_at', sa.DateTime(), nullable=False),
    sa.Column('primarySwellHeight', sa.Float(), nullable=False),
    sa.Column('primarySwellDirection', sa.String(length=120), nullable=False),
    sa.Column('primarySwellPeriod', sa.Float(), nullable=False),
    sa.Column('secondarySwellHeight', sa.Float(), nullable=False),
    sa.Column('secondarySwellDirection', sa.String(length=120), nullable=False),
    sa.Column('secondarySwellPeriod', sa.Float(), nullable=False),
    sa.Column('waveHeight', sa.Float(), nullable=False),
    sa.Column('windSpeed', sa.Float(), nullable=False),
    sa.Column('windDirection', sa.String(length=120), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('pressure', sa.Float(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_pressure'), ['pressure'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_primarySwellDirection'), ['primarySwellDirection'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_primarySwellHeight'), ['primarySwellHeight'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_primarySwellPeriod'), ['primarySwellPeriod'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_secondarySwellDirection'), ['secondarySwellDirection'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_secondarySwellHeight'), ['secondarySwellHeight'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_secondarySwellPeriod'), ['secondarySwellPeriod'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_session_at'), ['session_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_temperature'), ['temperature'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_waveHeight'), ['waveHeight'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_windDirection'), ['windDirection'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_windSpeed'), ['windSpeed'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_windSpeed'))
        batch_op.drop_index(batch_op.f('ix_session_windDirection'))
        batch_op.drop_index(batch_op.f('ix_session_waveHeight'))
        batch_op.drop_index(batch_op.f('ix_session_user_id'))
        batch_op.drop_index(batch_op.f('ix_session_temperature'))
        batch_op.drop_index(batch_op.f('ix_session_session_at'))
        batch_op.drop_index(batch_op.f('ix_session_secondarySwellPeriod'))
        batch_op.drop_index(batch_op.f('ix_session_secondarySwellHeight'))
        batch_op.drop_index(batch_op.f('ix_session_secondarySwellDirection'))
        batch_op.drop_index(batch_op.f('ix_session_primarySwellPeriod'))
        batch_op.drop_index(batch_op.f('ix_session_primarySwellHeight'))
        batch_op.drop_index(batch_op.f('ix_session_primarySwellDirection'))
        batch_op.drop_index(batch_op.f('ix_session_pressure'))
        batch_op.drop_index(batch_op.f('ix_session_created_at'))

    op.drop_table('session')
    # ### end Alembic commands ###
